### ISSUE TITLE
convert model to tflite

### ISSUE THREAD

**Issue by guitar9** [karasawatakumi/pytorch-image-classification#4]
I would like to run the model on my smartphone. Does somebody know how to convert the pytorch model to tflite?

**Comment by karasawatakumi** [comment]
@guitar9 
Thanks for the comment.  A quick search seem to hit repositories like this ([sithu31296/PyTorch-ONNX-TFLite](https://github.com/sithu31296/PyTorch-ONNX-TFLite), `PyTorch -> ONNX -> TF -> TFLite`). Also, the conversion to onnx is explained in the official pytorch lightning docs. ([Compile your model to ONNX](https://pytorch-lightning.readthedocs.io/en/latest/deploy/production_advanced.html#compile-your-model-to-onnx))
